- hosts: localhost
  pre_tasks:
    - name: Update cache
      become: true
      apt:
        update_cache: true
  tasks:
    - name: Install zsh
      become: true
      apt: name=zsh

    - name: Change shell
      become: true
      shell: chsh -s `which zsh`

    - name: Install ohmyzsh
      shell: curl -L https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh

    - name: Install Homebrew
      include_role:
        name: markosamuli.linuxbrew
      vars:
        linuxbrew_use_installer: true
        linuxbrew_init_shell: false
        linuxbrew_install_tmp: "{{ ansible_env.HOME }}/tmp/linuxbrew"

    - name: Install dotfiles
      include_role:
        name: hussainweb.chezmoi
      vars:
        chezmoi_init_url: "awarrington0895"

    - name: Install neovim and tmux
      community.general.homebrew:
        name:
          - fzf
          - ripgrep
          - neovim
          - tmux

    - name: Install tmux plugin manager
      git:
        repo: https://github.com/tmux-plugins/tpm
        dest: "{{ ansible_env.HOME }}/.config/tmux/plugins/tpm"
